name: CI/CD
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - name: Install node dependancies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Build config
        run: npm run build
      - name: Run test
        run: npm run test
      - name: Build docs
        run: npm run docs
      - name: Build dist
        run: npm run dist
      - name: Release
        run: npx semantic-release --branches master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
