name: Continuous Integration
on:
  push:
    branches:
      - '**'
  pull_request:
    types:
      - closed
jobs:
  if_push:
    name: Tests
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Install node dependancies
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Build config
        run: npm run build
      - name: Run test
        run: npm run test
      - name: Build docs
        run: npm run docs
      - name: Build dist
        run: npm run dist
      # - name: Release
      #   run: npx semantic-release@19.0.5 --branches master
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  if_pr_merged:
    name: Post build
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm ci
      - run: |
          npm run build
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./build
          git diff-index --quiet HEAD || git commit -m 'chore: automated post build' && git push
