name: Push
on:
  push:
    branches-ignore:
      - master
jobs:
  lint:
    name: Linters
    uses: ./.github/workflows/linters.yml
  build:
    name: Docs
    uses: ./.github/workflows/build.yml
  tests:
    name: Test
    uses: ./.github/workflows/test.yml
