name: Release
on:
  push:
    branches:
      - master
jobs:
  checks:
    name: Checks
    uses: ./.github/workflows/checks.yml
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npm
      - run: npx semantic-release@19.0.5 --branches master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
