name: Release
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  lint:
    name: Linters
    uses: ./.github/workflows/linters.yml
  build:
    name: Build
    uses: ./.github/workflows/build.yml
  tests:
    needs: [lint, build]
    name: Test
    uses: ./.github/workflows/test.yml
  release:
    needs: [tests]
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: npx semantic-release@19.0.5 --branches master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
